services:
    verturin.inmemoriam.legacy_manager:
        class: verturin\inmemoriam\core\legacy_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%core.table_prefix%'

    verturin.inmemoriam.group_manager:
        class: verturin\inmemoriam\core\group_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'

    verturin.inmemoriam.listener:
        class: verturin\inmemoriam\event\main_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '@user'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }

    verturin.inmemoriam.controller.legacy:
        class: verturin\inmemoriam\controller\legacy_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@verturin.inmemoriam.legacy_manager'
            - '%core.table_prefix%'
