services:
    verturin.inmemorium.legacy_manager:
        class: verturin\inmemorium\core\legacy_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%core.table_prefix%'

    verturin.inmemorium.group_manager:
        class: verturin\inmemorium\core\group_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'

    verturin.inmemorium.listener:
        class: verturin\inmemorium\event\main_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '@user'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }

    verturin.inmemorium.controller.legacy:
        class: verturin\inmemorium\controller\legacy_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@verturin.inmemorium.legacy_manager'
            - '%core.table_prefix%'
